spring:
#  jackson:
#    mapper:
#      accept-case-insensitive-enums: true
  threads:
    virtual:
      enabled: true
  application:
    name: stock-portfolio-advisor
  docker:
    compose:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/stock_advisor_db
    username: user
    password: password
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
#      data-locations: classpath:data.sql
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

# langchain4j configuration
langchain4j:
  ollama:
    chat-model:
      base-url: http://localhost:11434
      model-name: llama3.2
      log-requests: true
      log-responses: true
      temperature: 0.8
      timeout: PT120S
      # supported-capabilities: response_format_json_schema


fmg:
  api:
    v3:
#      endpoint: https://financialmodelingprep.com/stable
      endpoint: https://financialmodelingprep.com/api/v3

# logging configuration
logging:
#  pattern:
#    console: %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
  level:
    dev:
      langchain4j: DEBUG
      ai4j:
        ollama4j: DEBUG
